### ISSUE TITLE
proposal: re-organize settings inheritance for staging & production

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/django-project-template#102]
The fact that production settings inherit from staging settings is confusing and easily gets you into a state where you accidentally deploy a staging setting to production because you forgot to remove it in the production settings file.

I'd vote for having both files inherit from the same parent settings, or staging inheriting from production. More often than not, you'll want to disable or tweak certain things active on production (or add extra logging, for example) in the staging environment , rather than the other way around.

**Comment by mlavin** [comment]
In a more recent project we are taking the following approach to address this. We have removed the `staging` and `production` settings in favor of a single `live` settings. Settings are configured via environment variables. For the DB settings we use https://github.com/kennethreitz/dj-database-url. We do pass the name of the environment in the `os.environ` so we can have conditional settings blocks. For instance the `live` settings are used by the Vagrant setup and we disable email sending (write to the console).

**Comment by dpoirier** [comment]
This sounds good to me.
