### ISSUE TITLE
Allow PostgreSQL version/extension specification

### ISSUE THREAD

**Issue by copelco** [caktus/django-project-template#117]
Saving for a later ShipIt day. Use PostgreSQL's apt repository to allow specification of versions and extensions via Pillar:

```
postgresql_version: 9.3
postgresql_extensions: [postgis]
```

Files to update:

* Update [postgresql.init](https://github.com/codefordurham/school-inspector/pull/2/files#diff-f4b2cb589a6df6ba199f06a289140e48R1) and [default-locale.sh](https://github.com/codefordurham/school-inspector/pull/2/files#diff-216c63414c1bb5e793fb741855d81b71R1) in margarita
* Update [project.db.init](https://github.com/codefordurham/school-inspector/pull/2/files#diff-767f77651aabc4a38c76873444f5f752R1) along with [postgresql.conf](https://github.com/codefordurham/school-inspector/pull/2/files#diff-b4b462c82ae4bb9f3de2396cb3845fbfR38)

**Comment by vkurup** [comment]
The `version` portion of this has been completed. We'll track the `extension` piece over at caktus/margarita#13
