### ISSUE TITLE
Consider Making pylibmc the Default

### ISSUE THREAD

**Issue by mlavin** [caktus/django-project-template#15]
Currently using the `python-memcached` client which is pure Python and easy to install. Recently ran into some problems with this when there were a number of concurrent connections and switching to `pylibmc` increased the performance significantly. `pylibmc` is a client written in C and requires `libmemcached-dev` to compile. Previously avoided this when it wasn't needed because  `libmemcached-dev` was too old in Lucid to install. With more deployments going out on 12.04 this is no longer a problem.

**Comment by dpoirier** [comment]
It looks like in order to use Pylibmc, we'd have to support compiling it during deploys (or add some feature to our deploy code to pre-compile it ourselves).  Pylibmc doesn't have pre-compiled wheels available on PyPI.  Do we want to get into supporting compiling Pylibmc on our deployed servers on various hosting environments, as well as both Linux and Mac developer laptops?  

How much performance improvement are we talking about?

**Comment by mlavin** [comment]
If I can recall correctly from 4 years ago the difference was the server completely swamped memcached and it failed serving any requests to completely the benchmark without any errors. It might have been related to gevent + python-memcached no closing old connections more than python-memcached alone. So in my case it wasn't so much about a few ms, it was working >> not working.

**Comment by tobiasmcnulty** [comment]
Another consideration is the preferred behavior when memcached goes down. IIRC pylibmc will raise an exception if it fails to connect to the server, while python-memcached will not. IMO the latter is the correct behavior. I.e., the cache should improve the application's ability to serve requests efficiently without preventing the application from serving any requests should the cache go down.

	>>> import pylibmc
	>>> mc = pylibmc.Client(["127.0.0.1"])
	>>> mc.get('foo')
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	_pylibmc.ConnectionError: error 3 from memcached_get(foo): (0x7fa403700160) CONNECTION FAILURE, ::rec() returned zero, server has disconnected,  host: 127.0.0.1:11211 -> libmemcached/io.cc:484

	>>> import memcache
	>>> mc2 = memcache.Client(['127.0.0.1'])
	>>> mc2.get('foo')
	>>>

**Comment by tobiasmcnulty** [comment]
(FWIW, at some point after my 2013 comment we switched back to python-memcached on CCSR)

**Comment by mlavin** [comment]
So I think the right place for this issue is in the :fire:.

**Comment by tobiasmcnulty** [comment]
👍
