### ISSUE TITLE
Salt 2015.5.0 Breaking Changes

### ISSUE THREAD

**Issue by mlavin** [caktus/django-project-template#163]
New Salt release has a major change to the way `cmd` modules are run. http://docs.saltstack.com/en/latest/topics/releases/2015.5.0.html This may break any use of "pipe command through grep before running another command".

**Comment by mlavin** [comment]
While adding this and rereading the notes I'm not sure if that is true. It does say

> The largest side effect of this change is that "shellisms", such as pipes, will not work by default.

However, later it says

> Additionally, the cmd state module has been unaffected...

No idea how interpret this.

**Comment by dpoirier** [comment]
On Thu, May 14, 2015 at 9:43 AM, Mark Lavin <notifications@github.com>
wrote:

> This may break any use of "pipe command through grep before running
> another command".


​Also "cmd && cmd" or "cmd; cmd" or "cmd >filename".  Etc.​

**Comment by mlavin** [comment]
Yes there are at least two uses of `&&`.

**Comment by mlavin** [comment]
Summarizing the impacted states:

- Resetting the PG cluster encoding (https://github.com/caktus/margarita/issues/46)
- Installing LessCSS
- Generating the Nginx SSL cert
- Detecting Django migrations

**Comment by mlavin** [comment]
I think this have all been resolved or have open PRs.
