### ISSUE TITLE
Consider a .env file for configuring env vars for server processes

### ISSUE THREAD

**Issue by dpoirier** [caktus/django-project-template#166]
Right now we have multiple places in our deploy scripts where we have to list out all the env vars we want to set for the process we're starting (e.g. gunicorn, celery, ...). It would be simpler and less error-prone if we had a single file, conventionally named `.env`, where we specified all the vars and their values.

With [django-dotenv](https://github.com/jpadilla/django-dotenv), you can drop a couple of lines into manage.py or another file that gets run early and add all the vars from `.env` to the OS environment.

It's not hard to grab the env vars from a shell script either, just a one-liner: `export $(cat .env | grep -v ^# | xargs)`.

**Comment by mlavin** [comment]
:+1: to the idea. We've also run into problems putting these in the supervisor config because of `%` characters. We will need some thought as to where to put this though since we don't use `manage.py` for running gunicorn or the celery workers. We do use it for `migrate`, `collectstatic`, `etc`.

**Comment by vkurup** [comment]
Tracked by https://github.com/caktus/margarita/issues/65 now that the states are there. (Assuming that we're going to do this in the supervisor configs, and not with django-dotenv)

**Comment by mlavin** [comment]
We are currently doing this in the supervisor config so I think the idea would be to get away from that. There are likely changes in both places required to make this happen.

**Comment by vkurup** [comment]
Ahhh....Reopening.

My thought was that the change would be to stop explicitly listing out each env var in the supervisor config (like we do currently), but instead load all the env vars from a common .env file.

Now I understand that the idea is to remove the entire `environment` variable from the supervisor conf files and use django-dotenv here in just one place.

**Comment by vkurup** [comment]
[manage.py](https://github.com/caktus/django-project-template/blob/master/manage.py#L6) and [wsgi.py](https://github.com/caktus/django-project-template/blob/master/project_name/wsgi.py#L16) now properly load variables from `.env`. [Docs have been written](https://github.com/caktus/django-project-template/blob/master/docs/provisioning.rst#celery) to have celery.py load it as well, if celery is used for the project.

Closing.
