### ISSUE TITLE
Generate Diffie-Hellman parameters

### ISSUE THREAD

**Issue by lemanal** [caktus/django-project-template#188]
run: ``openssl dhparam -out dhparam.pem 4096``
or maybe 2048?

and use it in nginx.conf: ``ssl_dhparam /path/to/dhparam.pem;``

See:
* https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
* https://weakdh.org/sysadmin.html

**Comment by lemanal** [comment]
@kmtracey

**Comment by kmtracey** [comment]
Hmm, that openssl dhparam command says when it starts "This is going to take a long time". Do we have any idea how long? I gather it is indeterminate but do we have some idea of realistically how long this will take? (I gave up my quick try after 12 minutes...)

**Comment by lemanal** [comment]
Just took me an hour to run it with 4096

**Comment by dpoirier** [comment]
Only an hour?!

**Comment by mlavin** [comment]
1024 is the minimum that modern browsers are supposed to support. Most recommendations seem to state that 2048 is sufficient.

**Comment by dpoirier** [comment]
On my laptop, it took 18 minutes for 4096 bits, but only 69 seconds for 2048.  69 seconds still seems a bit long, but acceptable for something that only has to be done once on a system.

**Comment by vkurup** [comment]
caktus/margarita#62 is now tracking this.
