### ISSUE TITLE
lessc new install different location

### ISSUE THREAD

**Issue by daaray** [caktus/django-project-template#193]
@Scottm-Caktus provisioned a server for me this AM and we determined that less was being installed in an unexpected location.

The settings expect it to be at:

```
COMPRESS_PRECOMPILERS = (
    ('text/less', '/usr/local/bin/lessc {infile} {outfile}'),
)
```

Adjusting `settings.production.py` to:

```
COMPRESS_PRECOMPILERS = (
    ('text/less', '/usr/bin/lessc {infile} {outfile}'),
)
```

resolved our immediate issue.

**Comment by mlavin** [comment]
The current configuration just expects that `lessc` is on the `PATH`. It doesn't specify the full path.

**Comment by daaray** [comment]
Noted! Will adjust my project to conform to the current configuration:

```
# Application settings
COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc {infile} {outfile}'),
)
```
