### ISSUE TITLE
Consider using NPM as a standard source of frontend dependencies

### ISSUE THREAD

**Issue by ironfroggy** [caktus/django-project-template#215]
This is an interesting option: https://github.com/kevin1024/django-npm
I've also experimented with adding NPM installed tooling to a virtualenv, which could be added to project instructions.

**Comment by dpoirier** [comment]
That does look interesting. It doesn't seem to leave any room to insert something like browserify into the flow though. It'd be nice to be able to install the npm packages, use browserify to gather the javascript files that are actually needed and minify etc etc, then have collectstatic only grab the result of that as javascript.

**Comment by ironfroggy** [comment]
I would prefer a browserify direction, myself. django-npm is interesting if you just want NPM as a source, but going an extra step and really organizing our own JS better, as well, would be great. We've experimented with this in at least one project and could roll that into the template.
