### ISSUE TITLE
Optional Haystack States

### ISSUE THREAD

**Issue by mlavin** [caktus/django-project-template#43]
Similar to #40 it would be nice to have some states to quickly enable Haystack using either Solr or ElasticSearch.

**Comment by vkurup** [comment]
It's hard for me to tell if this has been completed (having never used solr, elasticsearch, or haystack), but there do appear to be solr states in margarita which post-date this issue. If not completed, we should move this issue to margarita.

**Comment by mlavin** [comment]
Yes I think this can be closed. Few projects using Haystack now. I've written some ElasticSearch states that I can contribute to margarita.

**Comment by vkurup** [comment]
Great, thanks!
