### ISSUE TITLE
Sudoers Assumption

### ISSUE THREAD

**Issue by mlavin** [caktus/django-project-template#44]
The provisioning/deployment changes using Salt have an assumption that the `admin` group has passwordless sudo rights. This seems to be true for the default Precise Vagrant box this is not a reasonable assumption in general. Previously the `create_users` Fabric task ensured that the `dev` group has passwordless sudo. We should add a state either here or in https://github.com/caktus/margarita to do the same.

**Comment by vkurup** [comment]
A sudoers file was added to margarita here: https://github.com/caktus/margarita/commit/12211482409f57859380445359c7906a986bdfb4

Should we create a separate issue over at margarita for the other changes? I'd also like the ability to view logs in /var/log/salt (for example), which currently requires root privs.

**Comment by mlavin** [comment]
The biggest problem with this has been addressed but these permissions could be much more restrictive.  Closing this and adding a follow up sounds good to me.
