### ISSUE TITLE
Auto secrets "sync" confusing to non-experts

### ISSUE THREAD

**Issue by kmtracey** [caktus/django-project-template#90]
There is no mention of the secrets file in the README, so devs who are coming to this new deployment scheme with little/no knowledge of what it's doing under the covers are typically going to have no idea what the secrets sync prompt is telling them, nor what they should do in response. If they assume "this thing knows what it is doing" and just say "yes" it seems that the result will be every non-expert dev reverting changes/additions made to the secrets file since their last deploy, as their out-of-date local secrets file will be pushed up to the server.

In general I think changes to secrets are expected to be rare? I think it would be preferable to have a specific command to push a changed secrets to the server, rather than to have deploy attempt to auto-detect local changes and prompt the user for what to do if the local file differs from remote. People who have to change secrets would then have to know/understand more, but in general they're going to anyway....if you're updating secrets you are doing something a bit beyond the normal make a code change/push to github/deploy to staging workflow that is the norm of most devs.

**Comment by mlavin** [comment]
I believe the largest of these concerns is addressed by #159.

**Comment by mlavin** [comment]
#159 has been merged and there is no magic sync. It is sync`d via git.
